--- #YAML:1.0
name:               JavaScript-V8
version:            0.02
abstract:           Perl interface to the V8
author:
    - Pawel Murias <pawelmurias@gmail.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::XSpp:  0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
