---
abstract: 'Perl interface to the V8 JavaScript engine'
author:
  - 'Pawel Murias <pawelmurias@gmail.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaScript-V8
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::XSpp: 0.11
resources:
  repository: http://github.com/dgl/javascript-v8
version: 0.07
